<a href="https://colab.research.google.com/github/jeffreyboschman/FiveMinuteMachineLearning/blob/main/deep_learning_basics/convolutions_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np
import torch

In [12]:
class convolution_2d_basic():
    def __init__(self, kernel_size, in_channels, out_channels, use_bias = True):
        self.kernel_size = kernel_size #e.g., 3x3
        self.in_channels = in_channels #e.g., 10
        self.out_channels = out_channels #e.g., 20

        self.filters = np.random.rand(out_channels, in_channels, kernel_size, kernel_size) #shape (C_out, C_in, k, k)
        if use_bias:
            self.bias =  np.random.rand(out_channels)

    def forward(input, output):
        '''
        Applies a 2d convolution on a set of input activations (e.g., an image) to get a set of output activations 

        input:  activations with shape (N, C_in, H_in, W_in)
        output: activations with shape (N, C_out, H_out, W_out)

        where N is batch size, C_in is the number of channels in the input, H_in is height of input (in pixels), W_in is width of input (in pixels),
                            C_out is the number of channels in the output, H_out is height of output (in pixels), W_out is width of output (in pixels)
        '''
        if len(input.shape) == 3:
            input = np.expand_dims(input, axis = 0)
        batch_size = input.shape[0]

        output = np.zeroes()
        pass


In [13]:
conv_test = convolution_2d_basic(3, 2, 2)
print(conv_test.filters)

[[[[0.561995   0.32681736 0.31022981]
   [0.22316832 0.31004083 0.37713426]
   [0.69949801 0.98897152 0.66373095]]

  [[0.50072492 0.51066451 0.71114483]
   [0.80999886 0.32266737 0.96974562]
   [0.11506431 0.48001288 0.96579405]]]


 [[[0.84262467 0.93084265 0.4474039 ]
   [0.84596426 0.71147594 0.47589435]
   [0.3564091  0.38941712 0.3972618 ]]

  [[0.56112824 0.79418605 0.76637691]
   [0.81511493 0.49033266 0.95786346]
   [0.44465248 0.69935138 0.03949969]]]]


In [28]:
input = np.random.rand(1, 2, 5, 5)
input = torch.tensor(input)
len(input.shape)

4